/** In-game economy guide — gold grind, materials, markets, sustainability */
const L = ['en', 'zh', 'es', 'pt', 'ko', 'ja', 'fr', 'de', 'ru', 'ar'];
const row = (en, zh, es, pt, ko, ja, fr, de, ru, ar) => {
    const v = [en, zh, es, pt, ko, ja, fr, de, ru, ar];
    const o = {};
    L.forEach((code, i) => { o[code] = v[i]; });
    return o;
};

export default {
    'economyGuide.title': row('Game Economy Guide', '游戏经济指南', 'Guía de economía', 'Guia da economia', '게임 경제 가이드', 'ゲーム経済ガイド', 'Guide économie', 'Wirtschaftsleitfaden', 'Гайд по экономике', 'دليل الاقتصاد'),
    'economyGuide.subtitle': row('How gold, materials, and markets work', '金币、物资与市场如何运作', 'Cómo funcionan oro, materiales y mercados', 'Como ouro, materiais e mercados funcionam', '골드·자원·마켓 작동 방식', 'ゴールド・素材・マーケットの仕組み', 'Or, matériaux et marchés', 'Gold, Materialien und Märkte', 'Как работают золото и рынки', 'كيف يعمل الذهب والموارد'),

    'economyGuide.currenciesHead': row('Three currencies', '三种货币', 'Tres monedas', 'Três moedas', '세 가지 화폐', '三つの通貨', 'Trois monnaies', 'Drei Währungen', 'Три валюты', 'ثلاث عملات'),
    'economyGuide.goldTitle': row('Gold', '金币', 'Oro', 'Ouro', '골드', 'ゴールド', 'Or', 'Gold', 'Золото', 'ذهب'),
    'economyGuide.goldDesc': row('In-game grind currency. Earn from fishing, wood, and daily orders. Spend on ferries, bait, casino, puffles, and PvP wagers (max 50g).', '游戏内刷取货币。钓鱼、伐木、每日订单获得。用于渡船、鱼饵、赌场、宠物与 PvP 赌注（上限 50 金）。', 'Moneda de farmeo. Gana pescando y madera. Gasta en ferris, cebo, casino y apuestas.', 'Moeda de grind. Ganhe pescando e madeira. Gaste em balsas, isca, cassino e apostas.', '인게임 그라인드 화폐. 낚시·벌목·일일 의뢰로 획득. 배·미끼·카지노·펭귄·PvP(최대 50)에 사용.', 'インディア通貨。釣り・伐採・デイリーで獲得。フェリー・餌・カジノ・ペット・PvP(最大50)に使用。', 'Monnaie de grind. Gagnez en pêchant et bois. Dépensez ferries, appâts, casino, paris.', 'Grind-Währung. Verdiene durch Angeln und Holz. Ausgeben für Fähren, Köder, Casino, Wetten.', 'Валюта гринда. Рыбалка, дерево, заказы. Трать на паромы, наживку, казино, ставки.', 'عملة اللعب. اكسب من الصيد والخشب. أنفق على العبّارات والطُعم والكازينو.'),
    'economyGuide.pebblesTitle': row('Pebbles', '卵石', 'Pebbles', 'Pebbles', '페블', 'ペブル', 'Pebbles', 'Pebbles', 'Pebbles', 'حصى'),
    'economyGuide.pebblesDesc': row('Premium currency (SOL-backed). Gacha rolls, Cosmetic Bazaar listings, and withdrawals. Not the same as gold.', '高级货币（SOL 支撑）。扭蛋、装扮集市挂牌与提现。与金币不同。', 'Moneda premium respaldada en SOL. Gacha y mercado de cosméticos.', 'Moeda premium com SOL. Gacha e bazar de cosméticos.', '프리미엄 화폐(SOL). 가챠·코스메틱 바자르. 골드와 별개.', 'プレミアム通貨(SOL)。ガチャ・コスメバザール。ゴールドとは別。', 'Monnaie premium (SOL). Gacha et bazar cosmétique.', 'Premium-Währung (SOL). Gacha und Kosmetik-Basar.', 'Премиум (SOL). Гача и базар косметики.', 'عملة مميزة (SOL). الجاتشا وسوق المستحضرات.'),
    'economyGuide.cpTitle': row('$CP token', '$CP 代币', 'Token $CP', 'Token $CP', '$CP 토큰', '$CPトークン', 'Jeton $CP', '$CP-Token', 'Токен $CP', 'رمز $CP'),
    'economyGuide.cpDesc': row('On-chain Solana utility: whale nametags, igloo rent, SPL wagers, daily bonus. Separate from gold grind.', '链上 Solana 效用：鲸鱼名牌、冰屋租金、SPL 赌注、每日奖励。与金币刷取分开。', 'Utilidad on-chain: nametags, iglús, apuestas SPL.', 'Utilidade on-chain: nametags, iglus, apostas SPL.', '온체인 솔라나: 고래 네임택, 이글루, SPL 베팅, 일일 보너스.', 'オンチェーン Solana：ネームタグ、イグルー、SPL賭け。', 'Utilité on-chain : nametags, igloos, paris SPL.', 'On-Chain Solana: Nametags, Iglus, SPL-Wetten.', 'On-chain: статусы, иглу, SPL-ставки.', 'سولانا على السلسلة: بطاقات، إيغلو، مراهنات.'),

    'economyGuide.loopHead': row('Gold grind loop', '金币刷取循环', 'Bucle de farmeo', 'Loop de grind', '골드 그라인드 루프', 'ゴールドループ', 'Boucle de grind', 'Gold-Grind-Schleife', 'Цикл гринда', 'حلقة جمع الذهب'),
    'economyGuide.loop1': row('Claim starter rod + worms → ferry to Snow Forts (1g)', '领取鱼竿与虫饵 → 渡船去雪堡（1 金）', 'Caña inicial → ferry a Snow Forts (1g)', 'Vara inicial → balsa Snow Forts (1g)', '스타터 낚싯대 → 스노 포트로 배(1g)', 'スターターロッド → スノーフォーツへ(1g)', 'Canne de départ → ferry Snow Forts (1g)', 'Startrute → Fähre Snow Forts (1g)', 'Удочка → паром Snow Forts (1g)', 'صنارة البداية → العبّارة (1 ذهب)'),
    'economyGuide.loop2': row('Fish ice holes (uses worms) → sell catch at Old Salty', '冰洞钓鱼（消耗虫）→ 向老盐卖鱼', 'Pesca en hielo → vende a Old Salty', 'Pesque → venda ao Old Salty', '얼음 구멍 낚시 → 솔티에게 판매', '氷穴で釣り → ソルティに売却', 'Pêchez → vendez à Old Salty', 'Angeln → verkaufen bei Old Salty', 'Рыбачьте → продайте Salty', 'اصطد → بع لسولتي'),
    'economyGuide.loop3': row('Ferry to Forest → chop wood, forage mossy logs for free worms', '渡船去森林 → 伐木，苔藓原木免费挖虫', 'Ferry al bosque → tala y busca gusanos', 'Balsa à floresta → corte madeira e minhocas', '숲으로 배 → 벌목, 이끼 통나무에서 미끼', '森へ → 伐採、苔ログで餌', 'Forêt → coupez bois, vers gratuits', 'Wald → Holz, Würmer sammeln', 'Лес → рубите, червей бесплатно', 'الغابة → اقطع واجمع ديدان'),
    'economyGuide.loop4': row('Return to town → Copper Clive: mint wood to gold or upgrade backpack (wood only)', '回城 → 克莱夫：木材铸金或升级背包（仅木材）', 'Ciudad → Clive: convierte madera o mejora mochila', 'Cidade → Clive: mint ou mochila (só madeira)', '마을 → 클라이브: 목재 환전·배낭(목재만)', '町 → クライブ：木材→金、リュック(木材のみ)', 'Ville → Clive : mint bois ou sac (bois)', 'Stadt → Clive: Holz→Gold, Rucksack (nur Holz)', 'Город → Clive: монета или рюкзак', 'المدينة → كليف: صك خشب أو حقيبة'),
    'economyGuide.loop5': row('Daily orders at Salty & Clive — contractor gold bonus for turning in materials', '萨蒂与克莱夫每日订单 — 上交物资获得承包商金币奖励', 'Pedidos diarios — bonus de oro por materiales', 'Pedidos diários — bônus em ouro', '솔티·클라이브 일일 의뢰 — 자재 제출 보너스', 'デイリー注文 — 素材納品ボーナス', 'Commandes quotidiennes — bonus or', 'Tagesaufträge — Gold-Bonus', 'Ежедневные заказы — бонус золота', 'طلبات يومية — مكافأة ذهب'),

    'economyGuide.earnHead': row('Ways to earn gold', '赚取金币的方式', 'Formas de ganar oro', 'Como ganhar ouro', '골드 획득 방법', 'ゴールドの稼ぎ方', 'Gagner de l\'or', 'Gold verdienen', 'Как заработать золото', 'كسب الذهب'),
    'economyGuide.earnFish': row('Emergency fish sell at Old Salty (~1g+ per catch at floor rates)', '紧急卖鱼（底价约每条 1 金+）', 'Venta de emergencia de pescado', 'Venda emergencial de peixe', '비상 생선 판매(최소 약 1g+)', '緊急魚売却(約1g+)', 'Vente d\'urgence poisson', 'Notverkauf Fisch', 'Срочная продажа рыбы', 'بيع طارئ للسمك'),
    'economyGuide.earnWood': row('Mint wood at Clive (best wood→gold path)', '克莱夫木材铸金（最佳木材换金路径）', 'Mint de madera en Clive', 'Mint de madeira no Clive', '클라이브 목재 환전(최고 효율)', 'クライブで木材→金', 'Mint bois chez Clive', 'Holz bei Clive prägen', 'Чеканка дерева у Clive', 'صك الخشب عند كليف'),
    'economyGuide.earnDaily': row('Daily contractor orders (2/day)', '每日承包商订单（每天 2 个）', 'Pedidos diarios (2/día)', 'Pedidos diários (2/dia)', '일일 의뢰(하루 2개)', 'デイリー注文(2/日)', 'Commandes quotidiennes (2/j)', 'Tagesaufträge (2/Tag)', 'Ежедневные заказы (2/день)', 'طلبات يومية (2/يوم)'),
    'economyGuide.earnSpinner': row('Daily prize wheel (planned) — free spin on cooldown; optional paid rolls in $CP only', '每日转盘（规划中）— 免费冷却；可选 $CP 付费', 'Ruleta diaria (planeada) — gratis con cooldown; pagos solo en $CP', 'Roleta diária (planejada) — grátis com cooldown; pagos só em $CP', '일일 룰렛(예정) — 무료 쿨다운; 유료는 $CP만', 'デイリールーレット（予定）— 無料＋$CP有料', 'Roue quotidienne (prévue) — gratuit + $CP payant', 'Tägliches Rad (geplant) — gratis + $CP-Zahlung', 'Колесо (план) — бесплатно + $CP', 'عجلة يومية (مخطط) — مجاني + $CP'),
    'economyGuide.spinnerHead': row('Daily prize wheel (planned)', '每日转盘（规划中）', 'Ruleta diaria (planeada)', 'Roleta diária (planejada)', '일일 룰렛(예정)', 'デイリールーレット（予定）', 'Roue quotidienne (prévue)', 'Tägliches Rad (geplant)', 'Ежедневное колесо (план)', 'عجلة يومية (مخطط)'),
    'economyGuide.spinnerDesc': row('Not live yet. When built: free spin + optional pay-to-roll using $CP (never competitor tokens). See docs/DAILY_SPINNER.md.', '尚未上线。上线后：免费转 + 可选 $CP 付费（非竞品代币）。见 docs/DAILY_SPINNER.md。', 'Aún no disponible. Pagos solo en $CP.', 'Ainda não disponível. Pagamentos só em $CP.', '미출시. $CP 유료만.', '未実装。$CPのみ。', 'Pas encore en ligne. Paiements en $CP uniquement.', 'Noch nicht live. Nur $CP.', 'Пока не в игре. Только $CP.', 'غير متاح بعد. $CP فقط.'),
    'economyGuide.earnScavenge': row('Trash scavenge (town ~10% chance, casino 20g/h)', '搜垃圾桶（城镇约 10% 概率，赌场 20 金/时）', 'Basura y casino', 'Lixeira e cassino', '쓰레기통·카지노', 'ゴミ箱・カジノ', 'Poubelles et casino', 'Mülltonnen & Casino', 'Мусорки и казино', 'سلة مهملات والكازينو'),
    'economyGuide.earnWager': row('Win PvP gold wagers (zero-sum, max 50g stake)', '赢得 PvP 金币赌注（零和，最高 50 金）', 'Gana apuestas PvP (máx 50g)', 'Vença apostas PvP (máx 50g)', 'PvP 골드 베팅 승리(최대 50g)', 'PvPゴールド賭け(最大50g)', 'Gagnez paris PvP (max 50g)', 'PvP-Goldwetten (max 50g)', 'PvP-ставки (макс 50g)', 'اربح مراهنات PvP'),

    'economyGuide.spendHead': row('What spends gold', '金币消耗', 'Gastos de oro', 'Gastos de ouro', '골드 소비', 'ゴールドの支出', 'Dépenses d\'or', 'Gold-Ausgaben', 'Куда тратить золото', 'مصروف الذهب'),
    'economyGuide.spendList': row('Ferries (1g) · worm bait bundles · gold slots & blackjack · puffles · PvP wagers', '渡船(1金)·虫饵·老虎机与二十一点·宠物·PvP 赌注', 'Ferris · cebo · casino · puffles · apuestas', 'Balsas · isca · cassino · puffles · apostas', '배(1g)·미끼·슬롯·BJ·펭귄·베팅', 'フェリー·餌·スロット·BJ·ペット·賭け', 'Ferries · appâts · casino · puffles · paris', 'Fähren · Köder · Casino · Puffles · Wetten', 'Паромы · наживка · казино · паффлы · ставки', 'عبّارات · طُعم · كازينو · مراهنات'),

    'economyGuide.materialsHead': row('Materials vs gold', '物资与金币', 'Materiales vs oro', 'Materiais vs ouro', '자원 vs 골드', '素材とゴールド', 'Matériaux vs or', 'Materialien vs Gold', 'Материалы и золото', 'الموارد مقابل الذهب'),
    'economyGuide.materialsDesc': row('Fish and wood are inventory items first. Tools, rods, axes, and backpack upgrades cost wood — not gold. Minting or emergency-selling converts extras to gold slowly.', '鱼与木材先入背包。工具、鱼竿、斧与背包升级消耗木材而非金币。铸金或紧急出售将多余物资缓慢换成金。', 'Peces y madera van al inventario. Mejoras cuestan madera.', 'Peixe e madeira no inventário. Upgrades custam madeira.', '물고기·목재는 인벤 우선. 업그레이드는 목재 비용.', '魚・木材はインベントリ優先。強化は木材。', 'Poisson et bois en inventaire. Améliorations en bois.', 'Fisch und Holz ins Inventar. Upgrades kosten Holz.', 'Рыба и дерево в инвентарь. Апгрейды за дерево.', 'السمك والخشب في المخزون. الترقيات بالخشب.'),

    'economyGuide.marketsHead': row('Two separate markets', '两个独立市场', 'Dos mercados separados', 'Dois mercados separados', '두 개의 별도 마켓', '二つの別マーケット', 'Deux marchés séparés', 'Zwei getrennte Märkte', 'Два рынка', 'سوقان منفصلان'),
    'economyGuide.marketCosmetic': row('Cosmetic Bazaar — Pebbles only. Trade gacha skins with players.', '装扮集市 — 仅卵石。与玩家交易扭蛋外观。', 'Bazar cosmético — solo Pebbles.', 'Bazar cosmético — só Pebbles.', '코스메틱 바자르 — 페블만.', 'コスメバザール — ペブルのみ。', 'Bazar cosmétique — Pebbles seulement.', 'Kosmetik-Basar — nur Pebbles.', 'Базар косметики — только Pebbles.', 'سوق المستحضرات — حصى فقط.'),
    'economyGuide.marketResource': row('Resource Exchange — coming later. Fish/wood for gold between players (not live yet).', '资源交易所 — 即将推出。玩家间鱼/木材换金（尚未上线）。', 'Intercambio de recursos — próximamente.', 'Bolsa de recursos — em breve.', '자원 거래소 — 추후. 플레이어 간 골드 거래(미출시).', 'リソース取引所 — 近日。プレイヤー間(未実装)。', 'Échange de ressources — bientôt.', 'Rohstoffbörse — später.', 'Биржа ресурсов — скоро.', 'بورصة الموارد — قريباً.'),

    'economyGuide.sustainHead': row('Why it stays balanced', '为何保持平衡', 'Por qué se equilibra', 'Por que fica equilibrado', '균형이 유지되는 이유', 'なぜ均衡が保たれるか', 'Pourquoi c\'est équilibré', 'Warum es ausgeglichen bleibt', 'Почему баланс держится', 'لماذا يبقى متوازناً'),
    'economyGuide.sustain1': row('Gold faucets (fish, wood, orders) are slow — expect ~30–60g/hour active grind.', '金币来源（鱼、木、订单）缓慢 — 积极刷取约每小时 30–60 金。', 'Grifos lentos — ~30–60g/hora.', 'Torneiras lentas — ~30–60g/hora.', '수도꼭지 느림 — 시간당 약 30–60g.', '蛇口は遅い — 約30–60g/時。', 'Robinets lents — ~30–60g/h.', 'Langsame Quellen — ~30–60g/h.', 'Медленные краны — ~30–60g/ч.', 'صنابير بطيئة — ~30–60 ذهب/ساعة.'),
    'economyGuide.sustain2': row('Sinks match play: ferries, bait, casino house edge, puffles, wagers.', '消耗与玩法匹配：渡船、鱼饵、赌场优势、宠物、赌注。', 'Sumideros: ferris, cebo, casino, puffles.', 'Sumidouros: balsas, isca, cassino.', '싱크: 배, 미끼, 카지노, 펭귄, 베팅.', 'シンク: フェリー・餌・カジノ等。', 'Éviers : ferries, appâts, casino.', 'Senken: Fähren, Köder, Casino.', 'Стоки: паромы, наживка, казино.', 'مصارف: عبّارات وطُعم وكازينو.'),
    'economyGuide.sustain3': row('Beat Sensei once in the Dojo for 1g (onboarding). After that, real stakes = PvP wagers only.', '道场击败 Sensei 一次得 1 金（新手）。之后真赌注 = PvP。', 'Vence a Sensei una vez en el Dojo por 1g. Luego = apuestas PvP.', 'Vença Sensei uma vez no Dojo por 1g. Depois = apostas PvP.', '도장에서 센세이 1회 승리 시 1g(온보딩). 이후 PvP만.', '道場でセンセイに1勝で1g（オンボ）。以降PvPのみ。', 'Battez Sensei une fois au Dojo pour 1g. Ensuite = paris PvP.', 'Sensei einmal im Dojo schlagen = 1g. Danach nur PvP.', 'Победи Sensei в додзё раз = 1g. Дальше только PvP.', 'اهزم Sensei مرة في الدوجو = 1 ذهب. بعدها PvP فقط.'),
    'economyGuide.sustain4': row('Server sets all prices — clients cannot fake payouts or listing prices.', '服务器定价 — 客户端无法伪造支付或挂牌价格。', 'El servidor fija precios — sin trampas cliente.', 'Servidor define preços.', '서버가 모든 가격 결정.', 'サーバーが全価格を決定。', 'Le serveur fixe les prix.', 'Server setzt alle Preise.', 'Сервер задаёт цены.', 'الخادم يحدد الأسعار.'),

    'economyGuide.notHead': row('What does NOT earn gold', '不能赚金币的方式', 'Qué NO da oro', 'O que NÃO dá ouro', '골드가 안 되는 것', 'ゴールドにならないもの', 'Ce qui ne donne PAS d\'or', 'Was KEIN Gold gibt', 'Что НЕ даёт золото', 'ما لا يمنح ذهباً'),
    'economyGuide.notList': row('Chat messages · repeat Dojo wins after onboarding · instant fish coins (fish go to backpack first) · selling Pebble cosmetics for gold', '聊天 · 重复道场胜利 · 即时鱼币（鱼先入背包）· 卵石装扮换金', 'Chat · Dojo repetido · monedas instantáneas de pescado', 'Chat · Dojo repetido · moedas instantâneas', '채팅 · 온보딩 후 도장 반복 · 즉시 코인(물고기는 인벤)', 'チャット・道場リピート・即コイン(魚はインベン)', 'Chat · dojo répété · pièces instantanées', 'Chat · wiederholtes Dojo · Sofort-Münzen', 'Чат · повтор додзё', 'الدردشة · تكرار الدوجو'),

    'economyGuide.close': row('Got it!', '明白了！', '¡Entendido!', 'Entendi!', '확인!', '了解！', 'Compris !', 'Verstanden!', 'Понятно!', 'فهمت!'),
};
